Vagrant.configure("2") do |config|
  config.vm.hostname = "fedora"
  config.vm.box = "fedora/33-cloud-base"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 1024
  end
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.provision "shell", inline: <<-SCRIPT
    echo "Installing ansible to run locally"
    dnf -y install ansible
    ansible-playbook /vagrant/main.yml
  SCRIPT
end
